"""app/pdf_tool.py — 使用 WeasyPrint 生成支持中文的 PDF

字体策略
--------
fonts/NotoSansSC-Regular.otf 硬编码进 CSS @font-face，
WeasyPrint 直接读取本地文件，无需任何系统字体，跨平台可用。

公开函数
--------
render_pdf(title, sections, output_path) -> Path
    最简调用：传标题 + 段落列表，返回生成的 PDF 路径。

示例
----
    from app.pdf_tool import render_pdf
    render_pdf(
        title="供应商核查报告",
        sections=[
            ("核查结论", "该供应商制造电耗申报值低于物理下限，存在造假嫌疑。"),
            ("法规依据", "Article 8(2)(c)：锂回收比例不得低于 6%。"),
        ],
        output_path="output/report.pdf",
    )

直接运行生成示例 PDF：
    python app/pdf_tool.py
"""
from __future__ import annotations

from pathlib import Path
from typing import List, Tuple

from jinja2 import Template
from weasyprint import CSS, HTML

# ── 路径常量 ──────────────────────────────────────────────────────────────────
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
_FONT_PATH    = _PROJECT_ROOT / "fonts" / "NotoSansSC-Regular.otf"
_OUTPUT_DIR   = _PROJECT_ROOT / "output"


def _check_font() -> None:
    if not _FONT_PATH.exists() or _FONT_PATH.stat().st_size < 1_000_000:
        raise FileNotFoundError(
            f"字体文件不存在或已损坏：{_FONT_PATH}\n"
            "请将 NotoSansSC-Regular.otf（约 8 MB）放入 fonts/ 目录。"
        )


# ── HTML 模板（Jinja2）────────────────────────────────────────────────────────
_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8"/>
<style>
  /* 硬编码本地字体路径，确保中文正确渲染 */
  @font-face {
    font-family: "NotoSC";
    src: url("{{ font_url }}") format("opentype");
    font-weight: normal;
    font-style: normal;
  }

  @page {
    size: A4;
    margin: 20mm 22mm 24mm 22mm;
    @bottom-center {
      content: "DPP Expert  |  第 " counter(page) " 页，共 " counter(pages) " 页";
      font-family: "NotoSC", sans-serif;
      font-size: 8pt;
      color: #999;
    }
  }

  body {
    font-family: "NotoSC", sans-serif;
    font-size: 11pt;
    color: #1a1a2e;
    line-height: 1.7;
  }

  h1 {
    font-size: 20pt;
    color: #0b3d91;
    border-bottom: 2px solid #0b3d91;
    padding-bottom: 6px;
    margin-bottom: 18px;
  }

  h2 {
    font-size: 13pt;
    color: #0b3d91;
    border-left: 4px solid #0b3d91;
    padding-left: 10px;
    margin-top: 24px;
    margin-bottom: 8px;
  }

  p {
    margin: 0 0 10px 0;
  }

  .footer-note {
    margin-top: 40px;
    font-size: 8.5pt;
    color: #999;
    border-top: 1px solid #ddd;
    padding-top: 8px;
  }
</style>
</head>
<body>

  <h1>{{ title }}</h1>

  {% for section_title, section_body in sections %}
  <h2>{{ section_title }}</h2>
  <p>{{ section_body }}</p>
  {% endfor %}

  <div class="footer-note">
    本报告由 DPP Expert 自动生成，仅供预审计参考，不构成法律意见。
    Generated by DPP Expert — EU 2023/1542 Compliance Engine.
  </div>

</body>
</html>
"""


# ── 核心函数 ──────────────────────────────────────────────────────────────────
def render_pdf(
    title: str,
    sections: List[Tuple[str, str]],
    output_path: str | Path = "output/report.pdf",
) -> Path:
    """生成一份支持中文的 PDF 报告。

    Parameters
    ----------
    title       : 报告大标题
    sections    : [(小标题, 正文), ...] 列表，每项渲染为一个带蓝色标题的段落
    output_path : 输出文件路径（默认 output/report.pdf）

    Returns
    -------
    Path : 生成的 PDF 文件绝对路径
    """
    _check_font()

    out = Path(output_path)
    if not out.is_absolute():
        out = _PROJECT_ROOT / out
    out.parent.mkdir(parents=True, exist_ok=True)

    # Jinja2 渲染 HTML
    html_str = Template(_HTML_TEMPLATE).render(
        title=title,
        sections=sections,
        font_url=_FONT_PATH.as_uri(),   # file:///... 本地路径，WeasyPrint 直接读取
    )

    # WeasyPrint 转 PDF
    HTML(string=html_str).write_pdf(str(out))

    print(f"[pdf_tool] PDF 已生成：{out}")
    return out


# ── 示例入口 ──────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    out_path = render_pdf(
        title="DPP Expert — 供应商核查示例报告",
        sections=[
            ("核查结论", "该供应商制造电耗申报值为 12 kWh/kWh，低于磷酸铁锂电池物理下限（20 kWh/kWh），当前工艺条件下不可能实现，判定为高风险造假数据。"),
            ("回收材料比例", "申报锂回收比例为 3%，低于欧盟 2023/1542 Article 8(2)(c) 规定的 2027 年最低值 6%，构成严重违规（NON_COMPLIANT）。"),
            ("法规依据", "Regulation (EU) 2023/1542, Article 8(2)(c)：batteries shall contain a minimum share of 6% of lithium recovered from battery waste, as of 18 August 2027."),
            ("建议措施", "请供应商提供经第三方机构（ASI / RMI）认证的回收材料溯源报告，并委托独立机构重新核算全生命周期制造能耗。"),
        ],
        output_path="output/sample_report.pdf",
    )
    print(f"请用 PDF 阅读器打开：{out_path}")
